export enum gameActionTypes {
  FETCH_USER_SCORE = 'FETCH_USER_SCORE',
  SET_DATA_USER = 'SET_DATA_USER',
  PLAYER_MOVE = 'PLAYER_MOVE',
  COMPUTER_MOVE = 'COMPUTER_MOVE',
  SET_MESSAGE = 'SET_MESSAGE',
  RESULT_GAME = 'RESULT_GAME',
  RESET_GAME = 'RESET_GAME',
}
