export enum gameActionTypes {
  SET_DATA_USER = 'SET_DATA_USER',
  PLAYER_MOVE = 'PLAYER_MOVE',
  COMPUTER_MOVE = 'COMPUTER_MOVE',
  RESULT_GAME = 'RESULT_GAME',
  PERSIST_RESULT = 'PERSIST_RESULT',
  RESET_GAME = 'RESET_GAME',
}
