export enum homeActionTypes {
  FETCH_USER = 'FETCH_USER',
  FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
  SET_USER = 'SET_USER',
  FETCH_SIGNIN_USER = 'FETCH_SIGNIN_USER',
  EXIT_USER = 'EXIT_USER',
}
